### ISSUE TITLE
return p values

### ISSUE THREAD

**Issue by RonDrabkin** [cdipaolo/linear#1]
Would you know if there is a package in Go that can take a CSV, runs regression analysis of the dataset and can return p values?  (bit of a newbie question here...new to Go, rusty at stats and new to GitHub)

**Comment by cdipaolo** [comment]
I'm assuming you're asking about finding the p-value as the two-tailed test that your data came from your linear model (linear regression.)

I don't know of any library that has this functionality built in, but you could use anything that gives you the line coefficients and then, as using a frequentist linear regression assumes, you could calculate the distribution of the error \epsilon ~ Normal(0, σ), and then use that distribution to compute the P-value. You could find a package pretty easily I would think that gives you the CDF of the normal distribution and then just calculate [from that](https://en.wikipedia.org/wiki/Linear_regression#Introduction_to_linear_regression).

I would mention, however, that Go is not the best language for statistics purposes in general, so unless this is a sub-feature of a real-time web-app or a learning opportunity (in which case you might just want to implement it yourself,) you might consider using tools built for the job like [Ccipy for Python](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.linregress.html) or [packages](https://github.com/JuliaStats/GLM.jl) for [Julia](http://docs.julialang.org/en/release-0.4/stdlib/linalg/#Base.linreg).
